// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDPuDiSKMZCxifu1tjPhBMk_Nliob4gg',
    appId: '1:667060220541:web:5e5bb4180d291879f53714',
    messagingSenderId: '667060220541',
    projectId: 'nutritrackmobile',
    authDomain: 'nutritrackmobile.firebaseapp.com',
    storageBucket: 'nutritrackmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP621sZwDzezG9cJK8ppWQY4K6NfhbR28',
    appId: '1:667060220541:android:f5949753369492d4f53714',
    messagingSenderId: '667060220541',
    projectId: 'nutritrackmobile',
    storageBucket: 'nutritrackmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp4yAJdK3PKo3lLdHiXwMXoECQMNvlFx4',
    appId: '1:667060220541:ios:d5f920d1dc1024edf53714',
    messagingSenderId: '667060220541',
    projectId: 'nutritrackmobile',
    storageBucket: 'nutritrackmobile.firebasestorage.app',
    iosBundleId: 'com.example.nutritrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp4yAJdK3PKo3lLdHiXwMXoECQMNvlFx4',
    appId: '1:667060220541:ios:d5f920d1dc1024edf53714',
    messagingSenderId: '667060220541',
    projectId: 'nutritrackmobile',
    storageBucket: 'nutritrackmobile.firebasestorage.app',
    iosBundleId: 'com.example.nutritrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDPuDiSKMZCxifu1tjPhBMk_Nliob4gg',
    appId: '1:667060220541:web:2eef88137b971135f53714',
    messagingSenderId: '667060220541',
    projectId: 'nutritrackmobile',
    authDomain: 'nutritrackmobile.firebaseapp.com',
    storageBucket: 'nutritrackmobile.firebasestorage.app',
  );
}
